### ISSUE TITLE
Docker image source

### ISSUE THREAD

**Issue by giuliocalzo** [jesperscherpenhuijsen/kubernetesmanifest#1]
Hi @jesperscherpenhuijsen how did you build the docker image for [jscherpe/managementconsole:11.1.0.2](https://github.com/jesperscherpenhuijsen/kubernetesmanifest/blob/main/RPA-basic%20clean.yaml#L101) and [jscherpe/roboserver:11.1.0.2](https://github.com/jesperscherpenhuijsen/kubernetesmanifest/blob/main/RPA-basic%20clean.yaml#L180), do you have dedicate repository for that?

**Comment by jesperscherpenhuijsen** [comment]
Hi @giuliocalzolari, these two videos describe the process of creating the Kofax RPA docker images: https://youtu.be/-9MpKnDvU_g and https://youtu.be/TjalCTyunHM
